In [2]:
import nltk
from nltk .tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import spacy 
import pandas as pd
import matplotlib.pyplot as plt
import re
from spacy import displacy
from nltk.stem import PorterStemmer

In [3]:
bbc = pd.read_csv("bbc_news.csv")

In [4]:
bbc.head()

,Unnamed: 0,index,title,pubDate,guid,link,description
0,0,6684,Can I refuse to work?,"Wed, 10 Aug 2022 15:46:18 GMT",https://www.bbc.co.uk/news/business-62147992,https://www.bbc.co.uk/news/business-62147992?a...,With much of the UK enduring another period of...
1,1,9267,'Liz Truss the Brief?' World reacts to UK poli...,"Mon, 17 Oct 2022 11:35:12 GMT",https://www.bbc.co.uk/news/world-63285480,https://www.bbc.co.uk/news/world-63285480?at_m...,The UK's political chaos has been watched arou...
2,2,7387,Rationing energy is nothing new for off-grid c...,"Wed, 31 Aug 2022 05:20:18 GMT",https://www.bbc.co.uk/news/uk-scotland-highlan...,https://www.bbc.co.uk/news/uk-scotland-highlan...,Scoraig in the north west Highlands has long h...
3,3,767,The hunt for superyachts of sanctioned Russian...,"Tue, 22 Mar 2022 14:37:01 GMT",https://www.bbc.co.uk/news/60739336,https://www.bbc.co.uk/news/60739336?at_medium=...,"Wealthy Russians sanctioned by the US, EU and ..."
4,4,3712,Platinum Jubilee: 70 years of the Queen in 70 ...,"Wed, 01 Jun 2022 23:17:33 GMT",https://www.bbc.co.uk/news/uk-61660128,https://www.bbc.co.uk/news/uk-61660128?at_medi...,A quick look back at the Queen's 70 years on t...

In [5]:
bbc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   1000 non-null   int64
 1   index        1000 non-null   int64
 2   title        1000 non-null   object
 3   pubDate      1000 non-null   object
 4   guid         1000 non-null   object
 5   link         1000 non-null   object
 6   description  1000 non-null   object
dtypes: int64(2), object(5)
memory usage: 54.8+ KB

In [6]:
title = pd.DataFrame(bbc['title'])
title.head()

                                               title
0                              Can I refuse to work?
1  'Liz Truss the Brief?' World reacts to UK poli...
2  Rationing energy is nothing new for off-grid c...
3  The hunt for superyachts of sanctioned Russian...
4  Platinum Jubilee: 70 years of the Queen in 70 ...

In [7]:
#Clean Data
title['lower'] = title['title'].str.lower()
title.head()

,title,lower
0,Can I refuse to work?,can i refuse to work?
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...

In [8]:
#StopWords
en_stopwords = stopwords.words('english')
en_stopwords.remove('not')
title["no_stopwords"] = title["lower"].apply(lambda x: " ".join([word for word in x.split() if word not in(en_stopwords)]))
title.head()

,title,lower,no_stopwords
0,Can I refuse to work?,can i refuse to work?,refuse work?
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds

In [9]:
#Punctuation Remove
title["no_stopwords_no_punct"] = title.apply(lambda x: re.sub(r"([^\w\s])","",  x['no_stopwords']), axis=1)
title.head()

,title,lower,no_stopwords,no_stopwords_no_punct
0,Can I refuse to work?,can i refuse to work?,refuse work?,refuse work
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...,liz truss brief world reacts uk political turmoil
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs,hunt superyachts sanctioned russian oligarchs
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds,platinum jubilee 70 years queen 70 seconds

In [10]:
#Tokenize
ps = PorterStemmer()
title["tokenize"] = title.apply(lambda x: word_tokenize(x["no_stopwords_no_punct"]), axis=1)
title.head()

,title,lower,no_stopwords,no_stopwords_no_punct,tokenize
0,Can I refuse to work?,can i refuse to work?,refuse work?,refuse work,"[refuse, work]"
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...,liz truss brief world reacts uk political turmoil,"[liz, truss, brief, world, reacts, uk, politic..."
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community,"[rationing, energy, nothing, new, offgrid, com..."
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs,hunt superyachts sanctioned russian oligarchs,"[hunt, superyachts, sanctioned, russian, oliga..."
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds,platinum jubilee 70 years queen 70 seconds,"[platinum, jubilee, 70, years, queen, 70, seco..."

In [11]:
#Lemmmatization
lemmatizer = WordNetLemmatizer()
title["lemmatized"] = title["tokenize"].apply(lambda tokens: [lemmatizer.lemmatize(token) for token in tokens])
title.head(20)

,title,lower,no_stopwords,no_stopwords_no_punct,tokenize,lemmatized
0,Can I refuse to work?,can i refuse to work?,refuse work?,refuse work,"[refuse, work]","[refuse, work]"
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...,liz truss brief world reacts uk political turmoil,"[liz, truss, brief, world, reacts, uk, politic...","[liz, truss, brief, world, reacts, uk, politic..."
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community,"[rationing, energy, nothing, new, offgrid, com...","[rationing, energy, nothing, new, offgrid, com..."
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs,hunt superyachts sanctioned russian oligarchs,"[hunt, superyachts, sanctioned, russian, oliga...","[hunt, superyachts, sanctioned, russian, oliga..."
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds,platinum jubilee 70 years queen 70 seconds,"[platinum, jubilee, 70, years, queen, 70, seco...","[platinum, jubilee, 70, year, queen, 70, second]"
5,Red Bull found guilty of breaking Formula 1's ...,red bull found guilty of breaking formula 1's ...,red bull found guilty breaking formula 1's bud...,red bull found guilty breaking formula 1s budg...,"[red, bull, found, guilty, breaking, formula, ...","[red, bull, found, guilty, breaking, formula, ..."
6,World Triathlon Championship Series: Flora Duf...,world triathlon championship series: flora duf...,world triathlon championship series: flora duf...,world triathlon championship series flora duff...,"[world, triathlon, championship, series, flora...","[world, triathlon, championship, series, flora..."
7,Terry Hall: Coventry scooter ride-out pays tri...,terry hall: coventry scooter ride-out pays tri...,terry hall: coventry scooter ride-out pays tri...,terry hall coventry scooter rideout pays tribu...,"[terry, hall, coventry, scooter, rideout, pays...","[terry, hall, coventry, scooter, rideout, pay,..."
8,Post Office and Fujitsu to face inquiry over H...,post office and fujitsu to face inquiry over h...,post office fujitsu face inquiry horizon scandal,post office fujitsu face inquiry horizon scandal,"[post, office, fujitsu, face, inquiry, horizon...","[post, office, fujitsu, face, inquiry, horizon..."
9,'Pavement parking frightens me','pavement parking frightens me','pavement parking frightens me',pavement parking frightens me,"[pavement, parking, frightens, me]","[pavement, parking, frightens, me]"
10,UK interest rates: How will the rise affect yo...,uk interest rates: how will the rise affect yo...,uk interest rates: rise affect high could go?,uk interest rates rise affect high could go,"[uk, interest, rates, rise, affect, high, coul...","[uk, interest, rate, rise, affect, high, could..."
11,They stayed for the storm - what happens now?,they stayed for the storm - what happens now?,stayed storm - happens now?,stayed storm happens now,"[stayed, storm, happens, now]","[stayed, storm, happens, now]"
12,Six Nations: Can Scotland's best since '99 bea...,six nations: can scotland's best since '99 bea...,six nations: scotland's best since '99 beat be...,six nations scotlands best since 99 beat best ...,"[six, nations, scotlands, best, since, 99, bea...","[six, nation, scotland, best, since, 99, beat,..."
13,How long can Liz Truss survive as prime minister?,how long can liz truss survive as prime minister?,long liz truss survive prime minister?,long liz truss survive prime minister,"[long, liz, truss, survive, prime, minister]","[long, liz, truss, survive, prime, minister]"
14,Platinum Jubilee: Beacons light across the glo...,platinum jubilee: beacons light across the glo...,platinum jubilee: beacons light across globe c...,platinum jubilee beacons light across globe ce...,"[platinum, jubilee, beacons, light, across, gl...","[platinum, jubilee, beacon, light, across, glo..."
15,Top student loan interest rate cut by 5% in En...,top student loan interest rate cut by 5% in en...,top student loan interest rate cut 5% england,top student loan interest rate cut 5 england,"[top, student, loan, interest, rate, cut, 5, e...","[top, student, loan, interest, rate, cut, 5, e..."
16,Russians said they’d take my baby: A medic’s s...,russians said they’d take my baby: a medic’s s...,russians said they’d take baby: medic’s story,russians said theyd take baby medics story,"[russians, said, theyd, take, baby, medics, st...","[russian, said, theyd, take, baby, medic, story]"
17,Week in pictures: 11-17 June 2022,week in pictures: 11-17 june 2022,week pictures: 11-17 june 2022,week pictures 1117 june 2022,"[week, pictures, 1117, june, 2022]","[week, picture, 1117, june, 2022]"
18,Xi Jinping in Hong Kong: Tight security as cit...,xi jinping in hong kong: tight security as cit...,xi jinping hong kong: tight security city mark...,xi jinping hong kong tight security city marks...,"[xi, jinping, hong, kong, tight, security, cit...","[xi, jinping, hong, kong, tight, security, cit..."
19,Rescues carried out in silence to listen for s...,rescues carried out in silence to listen for s...,rescues carried silence listen sounds life,rescues carried silence listen sounds life,"[rescues, carried, silence, listen, sounds, life]","[rescue, carried, silence, listen, sound, life]"

In [12]:
token_new_list = sum(title['tokenize'], [])
token_clean_list = sum(title['lemmatized'], [])

In [13]:
token_new_list

['refuse',
 'work',
 'liz',
 'truss',
 'brief',
 'world',
 'reacts',
 'uk',
 'political',
 'turmoil',
 'rationing',
 'energy',
 'nothing',
 'new',
 'offgrid',
 'community',
 'hunt',
 'superyachts',
 'sanctioned',
 'russian',
 'oligarchs',
 'platinum',
 'jubilee',
 '70',
 'years',
 'queen',
 '70',
 'seconds',
 'red',
 'bull',
 'found',
 'guilty',
 'breaking',
 'formula',
 '1s',
 'budget',
 'cap',
 'world',
 'triathlon',
 'championship',
 'series',
 'flora',
 'duffy',
 'beats',
 'georgia',
 'taylorbrown',
 'womens',
 'title',
 'terry',
 'hall',
 'coventry',
 'scooter',
 'rideout',
 'pays',
 'tribute',
 'singer',
 'post',
 'office',
 'fujitsu',
 'face',
 'inquiry',
 'horizon',
 'scandal',
 'pavement',
 'parking',
 'frightens',
 'me',
 'uk',
 'interest',
 'rates',
 'rise',
 'affect',
 'high',
 'could',
 'go',
 'stayed',
 'storm',
 'happens',
 'now',
 'six',
 'nations',
 'scotlands',
 'best',
 'since',
 '99',
 'beat',
 'best',
 'ireland',
 'ever',
 'long',
 'liz',
 'truss',
 'survive',
 'prime',
 'minister',
 'platinum',
 'jubilee',
 'beacons',
 'light',
 'across',
 'globe',
 'celebrate',
 'queens',
 'reign',
 'top',
 'student',
 'loan',
 'interest',
 'rate',
 'cut',
 '5',
 'england',
 'russians',
 'said',
 'theyd',
 'take',
 'baby',
 'medics',
 'story',
 'week',
 'pictures',
 '1117',
 'june',
 '2022',
 'xi',
 'jinping',
 'hong',
 'kong',
 'tight',
 'security',
 'city',
 'marks',
 '25',
 'years',
 'handover',
 'rescues',
 'carried',
 'silence',
 'listen',
 'sounds',
 'life',
 'nick',
 'pope',
 'newcastle',
 'goalkeeper',
 'extends',
 'incredible',
 'clean',
 'sheet',
 'record',
 'china',
 'plans',
 'become',
 'next',
 'big',
 'space',
 'power',
 'barcelona',
 'thrash',
 'leaders',
 'real',
 'madrid',
 'famous',
 'clasico',
 'win',
 'kuenssberg',
 'budget',
 'can',
 'not',
 'mask',
 'big',
 'changes',
 'economy',
 'nicola',
 'bulley',
 'search',
 'know',
 'disappearance',
 'cost',
 'living',
 'christmas',
 'lights',
 'displays',
 'survive',
 'energy',
 'crisis',
 '100yearold',
 'edinburgh',
 'man',
 'still',
 'working',
 'three',
 'days',
 'week',
 'freya',
 '600kg',
 'walrus',
 'causes',
 'stir',
 'norway',
 'offer',
 'uk',
 'home',
 'ukrainian',
 'refugees',
 'nicola',
 'bulley',
 'search',
 'former',
 'police',
 'boss',
 'says',
 'criticism',
 'unfair',
 'bolduc',
 'democrats',
 'elevated',
 'republican',
 'backfire',
 'strike',
 'action',
 'cancelled',
 'queens',
 'death',
 'neighbourhood',
 'leading',
 'green',
 'energy',
 'revolution',
 'mens',
 'u17',
 'european',
 'championship',
 'dutch',
 '17yearold',
 'isaac',
 'babadi',
 'scores',
 'panenka',
 'penalty',
 'amtrak',
 'derailment',
 'three',
 'killed',
 'missouri',
 'train',
 'hits',
 'truck',
 'energy',
 'price',
 'cap',
 'rising',
 'bills',
 'four',
 'discounts',
 'payments',
 'could',
 'help',
 'environment',
 'mushroom',
 'boards',
 'future',
 'surfing',
 'flying',
 'boats',
 'tech',
 'cleaner',
 'shipping',
 'scottish',
 'football',
 'ban',
 'heading',
 'day',
 'matches',
 'chris',
 'eubank',
 'jr',
 'v',
 'liam',
 'smith',
 'next',
 'boxing',
 'unacceptable',
 'taunts',
 'town',
 'destroyed',
 'make',
 'way',
 'whitesonly',
 'suburb',
 'ukraine',
 'war',
 'village',
 'celebrates',
 'russian',
 'retreat',
 'root',
 'hits',
 'ton',
 'england',
 'take',
 'command',
 'west',
 'indies',
 'heineken',
 'champions',
 'cup',
 'leicester',
 '166',
 'edinburgh',
 'jasper',
 'wiese',
 'try',
 'sends',
 'tigers',
 'last',
 'eight',
 'world',
 'cup',
 '2022',
 'bellingham',
 'gakpo',
 'fernandez',
 'breakout',
 'stars',
 'briton',
 'jack',
 'fenton',
 'killed',
 'greek',
 'helicopter',
 'accident',
 'emotional',
 'sue',
 'barker',
 'gets',
 'centre',
 'court',
 'ovation',
 'ukrainian',
 'skating',
 'sisters',
 'back',
 'doing',
 'love',
 'england',
 'v',
 'india',
 'edgbaston',
 'officials',
 'investigate',
 'crowd',
 'racism',
 'test',
 'newspaper',
 'headlines',
 'rwanda',
 'plan',
 'will',
 'fail',
 'sas',
 'train',
 'kyiv',
 'forces',
 'name',
 'leon',
 'sir',
 'lenny',
 'henry',
 'brings',
 'moving',
 'adoption',
 'story',
 'screen',
 'big',
 'brother',
 'star',
 'glyn',
 'wise',
 'plans',
 'priest',
 'ministers',
 'asleep',
 'wheel',
 'dentist',
 'shortages',
 'say',
 'lib',
 'dems',
 'chris',
 'kaba',
 'met',
 'suspends',
 'officer',
 'shot',
 'dead',
 'unarmed',
 'man',
 'world',
 'cup',
 '2022',
 'learned',
 'group',
 'stage',
 'saw',
 'record',
 'number',
 'upsets',
 'james',
 'webb',
 'nasa',
 'space',
 'telescope',
 'delivers',
 'spectacular',
 'pictures',
 'constitution',
 'hill',
 'cheltenham',
 'champion',
 'hurdle',
 'winner',
 'the',
 'horse',
 'generation',
 'least',
 'one',
 'victim',
 'could',
 'survived',
 'arena',
 'bomb',
 'inquiry',
 'gareth',
 'bale',
 'wales',
 'captain',
 'retires',
 'football',
 'aged',
 '33',
 'ukraine',
 'war',
 'silent',
 'streets',
 'wiped',
 'donetsk',
 'town',
 'world',
 'cup',
 '2022',
 'vittorio',
 'pozzos',
 'legacy',
 'record',
 'might',
 'finally',
 'threat',
 'train',
 'strikes',
 'workers',
 'vote',
 'six',
 'months',
 'walkouts',
 'eidevall',
 '100',
 'sure',
 'arsenal',
 'advance',
 'firstleg',
 'draw',
 'ukraine',
 'war',
 'returning',
 'place',
 'father',
 'killed',
 'furniture',
 'firm',
 'made',
 'collapse',
 'customers',
 'dark',
 'refunds',
 'widow',
 'us',
 'capitol',
 'riot',
 'officer',
 'stigma',
 'death',
 'nhs',
 'reaches',
 'deal',
 'lifesaving',
 'breastcancer',
 'drug',
 'giant',
 'ceramic',
 'sculpture',
 'sandy',
 'brown',
 'unveiled',
 'cornwall',
 'ceo',
 'secrets',
 'one',
 'company',
 'attracts',
 'men',
 'boris',
 'becker',
 'tennis',
 'superstar',
 'crashed',
 'earth',
 'turkish',
 'mine',
 'explosion',
 'kills',
 '25',
 'leaves',
 'dozens',
 'trapped',
 'indian',
 'wells',
 'andy',
 'murray',
 'emma',
 'raducanu',
 'jack',
 'draper',
 'win',
 'reach',
 'third',
 'round',
 'world',
 'athletics',
 'championships',
 'gbs',
 'keely',
 'hodgkinson',
 'narrowly',
 'misses',
 'gold',
 'dramatic',
 '800m',
 'nhs',
 'crisis',
 'medics',
 'trying',
 'fix',
 'health',
 'service',
 'jet',
 'crash',
 'block',
 'flats',
 'russia',
 'prince',
 'harry',
 'meghan',
 'get',
 'money',
 'chelsea',
 '42',
 'man',
 'utd',
 'chelsea',
 'win',
 'historic',
 'third',
 'successive',
 'wsl',
 'title',
 'tory',
 'leadership',
 'rather',
 'lose',
 'right',
 'thing',
 'says',
 'sunak',
 'omagh',
 'police',
 'shooting',
 'four',
 'men',
 'released',
 'john',
 'caldwell',
 'attack',
 'northern',
 'ireland',
 '10',
 'italy',
 'sarah',
 'mcfadden',
 'scores',
 'famous',
 'winner',
 'belfast',
 'actress',
 'clara',
 'darcy',
 'starring',
 'play',
 'brain',
 'tumour',
 'bridgerton',
 'south',
 'asian',
 'faces',
 'tv',
 'makes',
 'happy',
 'prince',
 'harry',
 'remembers',
 'queen',
 'elizabeth',
 'iis',
 'infectious',
 'smile',
 'millions',
 'receive',
 'latest',
 'costofliving',
 'payment',
 'joe',
 'biden',
 'heads',
 'middle',
 'east',
 'amid',
 'faltering',
 'us',
 'sway',
 'nhs',
 'public',
 'satisfaction',
 'health',
 'service',
 'drops',
 'record',
 'low',
 'seen',
 'major',
 'winter',
 'storms',
 'papers',
 'lions',
 'bare',
 'teeth',
 'starmers',
 'migration',
 'policy',
 'afghanistan',
 'pupils',
 'fear',
 'spate',
 'islamic',
 'state',
 'attacks',
 'princess',
 'wales',
 'kate',
 'pays',
 'tribute',
 'queen',
 'elizabeth',
 'carol',
 'service',
 'emma',
 'raducanu',
 'us',
 'open',
 'champion',
 'discusses',
 'tough',
 'split',
 'coach',
 'torben',
 'beltz',
 'oxford',
 'united',
 '03',
 'arsenal',
 'eddie',
 'nketiah',
 'scores',
 'twice',
 'gunners',
 'progress',
 'ukraine',
 'roundup',
 'putin',
 'defends',
 'necessary',
 'invasion',
 'kyiv',
 'averts',
 'cyberattack',
 'ni',
 'protocol',
 'uk',
 'eu',
 'reach',
 'agreement',
 'trade',
 'data',
 'sharing',
 'super',
 'mario',
 'bros',
 'movie',
 'jack',
 'black',
 'rise',
 'game',
 'adaptations',
 'fourtime',
 'slam',
 'champion',
 'osaka',
 'announces',
 'pregnancy',
 'mcdonalds',
 'cocacola',
 'boycott',
 'calls',
 'grow',
 'russia',
 'womens',
 'footballer',
 'year',
 'contender',
 'sam',
 'kerr',
 'war',
 'ukraine',
 'vladimir',
 'putin',
 'trained',
 'fighters',
 'africa',
 'ryanairs',
 'michael',
 'oleary',
 'wants',
 'practical',
 'immigration',
 'approach',
 'i',
 'planned',
 'end',
 'life',
 '16',
 'still',
 'here',
 'englands',
 '14',
 'men',
 'whipped',
 'twickenham',
 'crowd',
 'stirring',
 'display',
 'open',
 'rory',
 'mcilroy',
 'viktor',
 'hovland',
 'share',
 'lead',
 'st',
 'andrews',
 'third',
 'round',
 'real',
 'madrid',
 '20',
 'eintracht',
 'frankfurt',
 'karim',
 'benzema',
 'scores',
 '324th',
 'goal',
 'real',
 'super',
 'cup',
 'win',
 'papers',
 'boris',
 'dossier',
 'judges',
 'to',
 'back',
 'down',
 'rwanda',
 'queen',
 'pulls',
 'attending',
 'commonwealth',
 'service',
 'mosque',
 'fire',
 'suspect',
 'arrested',
 'second',
 'attack',
 'world',
 'cup',
 '2022',
 'belgium',
 'drop',
 'love',
 'away',
 'shirts',
 'qatar',
 'uks',
 'living',
 'covid',
 'plans',
 'sohos',
 'streets',
 'turned',
 'new',
 'london',
 'art',
 'gallery',
 'papers',
 'cruise',
 'ships',
 'house',
 'migrants',
 'new',
 'nhs',
 'cash',
 'pay',
 'gap',
 'bosses',
 'staff',
 'widen',
 'think',
 'tank',
 'local',
 'elections',
 'children',
 'urge',
 'action',
 'save',
 'wildlife',
 'climate',
 'change',
 'uk',
 'track',
 'meet',
 'targets',
 'trump',
 'investigation',
 'empty',
 'folders',
 'marked',
 'classified',
 'found',
 'maralago',
 'jim',
 'ratcliffe',
 'man',
 'bidding',
 'man',
 'utd',
 'shropshire',
 'baby',
 'deaths',
 'parents',
 'whose',
 'lives',
 'changed',
 'forever',
 'bus',
 'journeys',
 'taken',
 'since',
 '2',
 'fare',
 'cap',
 'says',
 'watchdog',
 'mexico',
 'kidnapping',
 'twisted',
 'moral',
 'code',
 'explains',
 'cartels',
 'apology',
 'rail',
 'fares',
 'england',
 'rise',
 'inflation',
 'rate',
 'ministers',
 'say',
 'taliban',
 'schools',
 'uturn',
 'a',
 'devastating',
 'day',
 'afghan',
 'girls',
 'malala',
 'yousafzai',
 'met',
 'police',
 'next',
 'force',
 'casey',
 'review',
 'ukraine',
 'war',
 'kherson',
 'mariupol',
 'key',
 'russian',
 'success',
 'heineken',
 'champions',
 'cup',
 'premiership',
 'cap',
 'hinders',
 'english',
 'teams',
 'alex',
 'sanderson',
 'ukraine',
 'war',
 'protester',
 'exposes',
 'cracks',
 'kremlins',
 'war',
 'message',
 'liz',
 'truss',
 'vows',
 'match',
 'ukraine',
 'military',
 'support',
 'politics',
 'returns',
 'wales',
 'population',
 'hits',
 'new',
 'high',
 'growth',
 'lowest',
 'many',
 'ukrainians',
 'fled',
 'homes',
 'gone',
 'deloitte',
 'report',
 'european',
 'football',
 'made',
 'significant',
 'recovery',
 'covid',
 'pandemic',
 'nigeria',
 'floods',
 'overwhelming',
 'disaster',
 'leaves',
 '600',
 'people',
 'dead',
 'wimbledon',
 'emma',
 'raducanu',
 'andy',
 'murray',
 'set',
 'centre',
 'court',
 'day',
 'one',
 'journey',
 'site',
 'nord',
 ...]

In [14]:
token_clean_list

['refuse',
 'work',
 'liz',
 'truss',
 'brief',
 'world',
 'reacts',
 'uk',
 'political',
 'turmoil',
 'rationing',
 'energy',
 'nothing',
 'new',
 'offgrid',
 'community',
 'hunt',
 'superyachts',
 'sanctioned',
 'russian',
 'oligarch',
 'platinum',
 'jubilee',
 '70',
 'year',
 'queen',
 '70',
 'second',
 'red',
 'bull',
 'found',
 'guilty',
 'breaking',
 'formula',
 '1',
 'budget',
 'cap',
 'world',
 'triathlon',
 'championship',
 'series',
 'flora',
 'duffy',
 'beat',
 'georgia',
 'taylorbrown',
 'womens',
 'title',
 'terry',
 'hall',
 'coventry',
 'scooter',
 'rideout',
 'pay',
 'tribute',
 'singer',
 'post',
 'office',
 'fujitsu',
 'face',
 'inquiry',
 'horizon',
 'scandal',
 'pavement',
 'parking',
 'frightens',
 'me',
 'uk',
 'interest',
 'rate',
 'rise',
 'affect',
 'high',
 'could',
 'go',
 'stayed',
 'storm',
 'happens',
 'now',
 'six',
 'nation',
 'scotland',
 'best',
 'since',
 '99',
 'beat',
 'best',
 'ireland',
 'ever',
 'long',
 'liz',
 'truss',
 'survive',
 'prime',
 'minister',
 'platinum',
 'jubilee',
 'beacon',
 'light',
 'across',
 'globe',
 'celebrate',
 'queen',
 'reign',
 'top',
 'student',
 'loan',
 'interest',
 'rate',
 'cut',
 '5',
 'england',
 'russian',
 'said',
 'theyd',
 'take',
 'baby',
 'medic',
 'story',
 'week',
 'picture',
 '1117',
 'june',
 '2022',
 'xi',
 'jinping',
 'hong',
 'kong',
 'tight',
 'security',
 'city',
 'mark',
 '25',
 'year',
 'handover',
 'rescue',
 'carried',
 'silence',
 'listen',
 'sound',
 'life',
 'nick',
 'pope',
 'newcastle',
 'goalkeeper',
 'extends',
 'incredible',
 'clean',
 'sheet',
 'record',
 'china',
 'plan',
 'become',
 'next',
 'big',
 'space',
 'power',
 'barcelona',
 'thrash',
 'leader',
 'real',
 'madrid',
 'famous',
 'clasico',
 'win',
 'kuenssberg',
 'budget',
 'can',
 'not',
 'mask',
 'big',
 'change',
 'economy',
 'nicola',
 'bulley',
 'search',
 'know',
 'disappearance',
 'cost',
 'living',
 'christmas',
 'light',
 'display',
 'survive',
 'energy',
 'crisis',
 '100yearold',
 'edinburgh',
 'man',
 'still',
 'working',
 'three',
 'day',
 'week',
 'freya',
 '600kg',
 'walrus',
 'cause',
 'stir',
 'norway',
 'offer',
 'uk',
 'home',
 'ukrainian',
 'refugee',
 'nicola',
 'bulley',
 'search',
 'former',
 'police',
 'bos',
 'say',
 'criticism',
 'unfair',
 'bolduc',
 'democrat',
 'elevated',
 'republican',
 'backfire',
 'strike',
 'action',
 'cancelled',
 'queen',
 'death',
 'neighbourhood',
 'leading',
 'green',
 'energy',
 'revolution',
 'men',
 'u17',
 'european',
 'championship',
 'dutch',
 '17yearold',
 'isaac',
 'babadi',
 'score',
 'panenka',
 'penalty',
 'amtrak',
 'derailment',
 'three',
 'killed',
 'missouri',
 'train',
 'hit',
 'truck',
 'energy',
 'price',
 'cap',
 'rising',
 'bill',
 'four',
 'discount',
 'payment',
 'could',
 'help',
 'environment',
 'mushroom',
 'board',
 'future',
 'surfing',
 'flying',
 'boat',
 'tech',
 'cleaner',
 'shipping',
 'scottish',
 'football',
 'ban',
 'heading',
 'day',
 'match',
 'chris',
 'eubank',
 'jr',
 'v',
 'liam',
 'smith',
 'next',
 'boxing',
 'unacceptable',
 'taunt',
 'town',
 'destroyed',
 'make',
 'way',
 'whitesonly',
 'suburb',
 'ukraine',
 'war',
 'village',
 'celebrates',
 'russian',
 'retreat',
 'root',
 'hit',
 'ton',
 'england',
 'take',
 'command',
 'west',
 'indie',
 'heineken',
 'champion',
 'cup',
 'leicester',
 '166',
 'edinburgh',
 'jasper',
 'wiese',
 'try',
 'sends',
 'tiger',
 'last',
 'eight',
 'world',
 'cup',
 '2022',
 'bellingham',
 'gakpo',
 'fernandez',
 'breakout',
 'star',
 'briton',
 'jack',
 'fenton',
 'killed',
 'greek',
 'helicopter',
 'accident',
 'emotional',
 'sue',
 'barker',
 'get',
 'centre',
 'court',
 'ovation',
 'ukrainian',
 'skating',
 'sister',
 'back',
 'doing',
 'love',
 'england',
 'v',
 'india',
 'edgbaston',
 'official',
 'investigate',
 'crowd',
 'racism',
 'test',
 'newspaper',
 'headline',
 'rwanda',
 'plan',
 'will',
 'fail',
 'sa',
 'train',
 'kyiv',
 'force',
 'name',
 'leon',
 'sir',
 'lenny',
 'henry',
 'brings',
 'moving',
 'adoption',
 'story',
 'screen',
 'big',
 'brother',
 'star',
 'glyn',
 'wise',
 'plan',
 'priest',
 'minister',
 'asleep',
 'wheel',
 'dentist',
 'shortage',
 'say',
 'lib',
 'dems',
 'chris',
 'kaba',
 'met',
 'suspends',
 'officer',
 'shot',
 'dead',
 'unarmed',
 'man',
 'world',
 'cup',
 '2022',
 'learned',
 'group',
 'stage',
 'saw',
 'record',
 'number',
 'upset',
 'james',
 'webb',
 'nasa',
 'space',
 'telescope',
 'delivers',
 'spectacular',
 'picture',
 'constitution',
 'hill',
 'cheltenham',
 'champion',
 'hurdle',
 'winner',
 'the',
 'horse',
 'generation',
 'least',
 'one',
 'victim',
 'could',
 'survived',
 'arena',
 'bomb',
 'inquiry',
 'gareth',
 'bale',
 'wale',
 'captain',
 'retires',
 'football',
 'aged',
 '33',
 'ukraine',
 'war',
 'silent',
 'street',
 'wiped',
 'donetsk',
 'town',
 'world',
 'cup',
 '2022',
 'vittorio',
 'pozzos',
 'legacy',
 'record',
 'might',
 'finally',
 'threat',
 'train',
 'strike',
 'worker',
 'vote',
 'six',
 'month',
 'walkout',
 'eidevall',
 '100',
 'sure',
 'arsenal',
 'advance',
 'firstleg',
 'draw',
 'ukraine',
 'war',
 'returning',
 'place',
 'father',
 'killed',
 'furniture',
 'firm',
 'made',
 'collapse',
 'customer',
 'dark',
 'refund',
 'widow',
 'u',
 'capitol',
 'riot',
 'officer',
 'stigma',
 'death',
 'nh',
 'reach',
 'deal',
 'lifesaving',
 'breastcancer',
 'drug',
 'giant',
 'ceramic',
 'sculpture',
 'sandy',
 'brown',
 'unveiled',
 'cornwall',
 'ceo',
 'secret',
 'one',
 'company',
 'attracts',
 'men',
 'boris',
 'becker',
 'tennis',
 'superstar',
 'crashed',
 'earth',
 'turkish',
 'mine',
 'explosion',
 'kill',
 '25',
 'leaf',
 'dozen',
 'trapped',
 'indian',
 'well',
 'andy',
 'murray',
 'emma',
 'raducanu',
 'jack',
 'draper',
 'win',
 'reach',
 'third',
 'round',
 'world',
 'athletics',
 'championship',
 'gb',
 'keely',
 'hodgkinson',
 'narrowly',
 'miss',
 'gold',
 'dramatic',
 '800m',
 'nh',
 'crisis',
 'medic',
 'trying',
 'fix',
 'health',
 'service',
 'jet',
 'crash',
 'block',
 'flat',
 'russia',
 'prince',
 'harry',
 'meghan',
 'get',
 'money',
 'chelsea',
 '42',
 'man',
 'utd',
 'chelsea',
 'win',
 'historic',
 'third',
 'successive',
 'wsl',
 'title',
 'tory',
 'leadership',
 'rather',
 'lose',
 'right',
 'thing',
 'say',
 'sunak',
 'omagh',
 'police',
 'shooting',
 'four',
 'men',
 'released',
 'john',
 'caldwell',
 'attack',
 'northern',
 'ireland',
 '10',
 'italy',
 'sarah',
 'mcfadden',
 'score',
 'famous',
 'winner',
 'belfast',
 'actress',
 'clara',
 'darcy',
 'starring',
 'play',
 'brain',
 'tumour',
 'bridgerton',
 'south',
 'asian',
 'face',
 'tv',
 'make',
 'happy',
 'prince',
 'harry',
 'remembers',
 'queen',
 'elizabeth',
 'ii',
 'infectious',
 'smile',
 'million',
 'receive',
 'latest',
 'costofliving',
 'payment',
 'joe',
 'biden',
 'head',
 'middle',
 'east',
 'amid',
 'faltering',
 'u',
 'sway',
 'nh',
 'public',
 'satisfaction',
 'health',
 'service',
 'drop',
 'record',
 'low',
 'seen',
 'major',
 'winter',
 'storm',
 'paper',
 'lion',
 'bare',
 'teeth',
 'starmers',
 'migration',
 'policy',
 'afghanistan',
 'pupil',
 'fear',
 'spate',
 'islamic',
 'state',
 'attack',
 'princess',
 'wale',
 'kate',
 'pay',
 'tribute',
 'queen',
 'elizabeth',
 'carol',
 'service',
 'emma',
 'raducanu',
 'u',
 'open',
 'champion',
 'discusses',
 'tough',
 'split',
 'coach',
 'torben',
 'beltz',
 'oxford',
 'united',
 '03',
 'arsenal',
 'eddie',
 'nketiah',
 'score',
 'twice',
 'gunner',
 'progress',
 'ukraine',
 'roundup',
 'putin',
 'defends',
 'necessary',
 'invasion',
 'kyiv',
 'averts',
 'cyberattack',
 'ni',
 'protocol',
 'uk',
 'eu',
 'reach',
 'agreement',
 'trade',
 'data',
 'sharing',
 'super',
 'mario',
 'bros',
 'movie',
 'jack',
 'black',
 'rise',
 'game',
 'adaptation',
 'fourtime',
 'slam',
 'champion',
 'osaka',
 'announces',
 'pregnancy',
 'mcdonalds',
 'cocacola',
 'boycott',
 'call',
 'grow',
 'russia',
 'womens',
 'footballer',
 'year',
 'contender',
 'sam',
 'kerr',
 'war',
 'ukraine',
 'vladimir',
 'putin',
 'trained',
 'fighter',
 'africa',
 'ryanairs',
 'michael',
 'oleary',
 'want',
 'practical',
 'immigration',
 'approach',
 'i',
 'planned',
 'end',
 'life',
 '16',
 'still',
 'here',
 'england',
 '14',
 'men',
 'whipped',
 'twickenham',
 'crowd',
 'stirring',
 'display',
 'open',
 'rory',
 'mcilroy',
 'viktor',
 'hovland',
 'share',
 'lead',
 'st',
 'andrew',
 'third',
 'round',
 'real',
 'madrid',
 '20',
 'eintracht',
 'frankfurt',
 'karim',
 'benzema',
 'score',
 '324th',
 'goal',
 'real',
 'super',
 'cup',
 'win',
 'paper',
 'boris',
 'dossier',
 'judge',
 'to',
 'back',
 'down',
 'rwanda',
 'queen',
 'pull',
 'attending',
 'commonwealth',
 'service',
 'mosque',
 'fire',
 'suspect',
 'arrested',
 'second',
 'attack',
 'world',
 'cup',
 '2022',
 'belgium',
 'drop',
 'love',
 'away',
 'shirt',
 'qatar',
 'uk',
 'living',
 'covid',
 'plan',
 'soho',
 'street',
 'turned',
 'new',
 'london',
 'art',
 'gallery',
 'paper',
 'cruise',
 'ship',
 'house',
 'migrant',
 'new',
 'nh',
 'cash',
 'pay',
 'gap',
 'boss',
 'staff',
 'widen',
 'think',
 'tank',
 'local',
 'election',
 'child',
 'urge',
 'action',
 'save',
 'wildlife',
 'climate',
 'change',
 'uk',
 'track',
 'meet',
 'target',
 'trump',
 'investigation',
 'empty',
 'folder',
 'marked',
 'classified',
 'found',
 'maralago',
 'jim',
 'ratcliffe',
 'man',
 'bidding',
 'man',
 'utd',
 'shropshire',
 'baby',
 'death',
 'parent',
 'whose',
 'life',
 'changed',
 'forever',
 'bus',
 'journey',
 'taken',
 'since',
 '2',
 'fare',
 'cap',
 'say',
 'watchdog',
 'mexico',
 'kidnapping',
 'twisted',
 'moral',
 'code',
 'explains',
 'cartel',
 'apology',
 'rail',
 'fare',
 'england',
 'rise',
 'inflation',
 'rate',
 'minister',
 'say',
 'taliban',
 'school',
 'uturn',
 'a',
 'devastating',
 'day',
 'afghan',
 'girl',
 'malala',
 'yousafzai',
 'met',
 'police',
 'next',
 'force',
 'casey',
 'review',
 'ukraine',
 'war',
 'kherson',
 'mariupol',
 'key',
 'russian',
 'success',
 'heineken',
 'champion',
 'cup',
 'premiership',
 'cap',
 'hinders',
 'english',
 'team',
 'alex',
 'sanderson',
 'ukraine',
 'war',
 'protester',
 'expose',
 'crack',
 'kremlin',
 'war',
 'message',
 'liz',
 'truss',
 'vow',
 'match',
 'ukraine',
 'military',
 'support',
 'politics',
 'return',
 'wale',
 'population',
 'hit',
 'new',
 'high',
 'growth',
 'lowest',
 'many',
 'ukrainian',
 'fled',
 'home',
 'gone',
 'deloitte',
 'report',
 'european',
 'football',
 'made',
 'significant',
 'recovery',
 'covid',
 'pandemic',
 'nigeria',
 'flood',
 'overwhelming',
 'disaster',
 'leaf',
 '600',
 'people',
 'dead',
 'wimbledon',
 'emma',
 'raducanu',
 'andy',
 'murray',
 'set',
 'centre',
 'court',
 'day',
 'one',
 'journey',
 'site',
 'nord',
 ...]

In [15]:
#POS Tagging
nlp = spacy.load('en_core_web_sm')

In [16]:
spacy_doc = nlp("".join(token_new_list))

In [17]:
pos_df = pd.DataFrame(columns=['token','pos_tag'])

In [18]:
for token in spacy_doc:
    pos_df = pd.concat([pos_df, pd.DataFrame.from_records([{'token': token.text, "pos_tag":token.pos_}])], ignore_index=True)

In [19]:
pos_df_counts = pos_df.groupby(['token','pos_tag']).size().reset_index(name='counts').sort_values(by='counts',ascending=False)
pos_df_counts.head()

                                               token pos_tag  counts
0  refuseworkliztrussbriefworldreactsukpoliticalt...    VERB       1

In [20]:
nouns = pos_df_counts[pos_df_counts.pos_tag=='NOUN'][0:10]
nouns

Empty DataFrame
Columns: [token, pos_tag, counts]
Index: []

In [21]:
#NER
ner_df = pd.DataFrame(columns=['token', 'ner_tag'])

for token in spacy_doc.ents:
    if pd.isna(token.label_) is False:
       ner_df = pd.concat([ner_df, pd.DataFrame.from_records([{'token': token.text, "ner_tag":token.label_}])], ignore_index=True)

In [22]:
ner_df.head(10)

Empty DataFrame
Columns: [token, ner_tag]
Index: []

In [23]:
#Displacy
# Import these at the top of your notebook
from IPython.display import HTML, display

# ... your other code to create spacy_doc ...

# Tell displacy not to auto-render, and just return the HTML
html = displacy.render(spacy_doc, style='ent', jupyter=False)

# Now, manually display the HTML string
display(HTML(html))

c:\Users\Al Madina Computer\OneDrive\Documents\pandasApp\.venv\Lib\site-packages\spacy\displacy\__init__.py:213: UserWarning: [W006] No entities to visualize found in Doc object. If this is surprising to you, make sure the Doc was processed using a model that supports named entity recognition, and check the `doc.ents` property manually if necessary.
  warnings.warn(Warnings.W006)